#!/usr/bin/env python3
"""One-shot generator for config/sources/*.yaml. Safe to re-run."""

from __future__ import annotations

from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "config" / "sources"
REVIEWED = "2026-08-15"


def src(**kwargs):
    row = {
        "schema": "source_definition.v1",
        "topics": [],
        "regions": ["global"],
        "languages": ["en"],
        "corroboration_required": True,
        "robots_policy": "obey",
        "rate_limit": {"requests_per_second": 0.2},
        "retention": {"raw_days": 90, "normalized_days": 0},
        "project_hints": [],
        "collection_mode": "scheduled",
        "extract_outbound_evidence_links": True,
        "automatic_content_eligible": False,
        "automatic_evidence_promotion": False,
        "enabled": False,
        "owner": "intelligence",
        "reviewed_at": REVIEWED,
    }
    row.update(kwargs)
    if row.get("enabled") is False and not row.get("disabled_reason"):
        row["disabled_reason"] = "registered; not in the active daily set"
    if row.get("tier") in {"T0", "T1"} and "automatic_content_eligible" not in kwargs:
        row["automatic_content_eligible"] = True
        row["automatic_evidence_promotion"] = True
        row["corroboration_required"] = kwargs.get("corroboration_required", False)
    if row.get("tier") in {"T4", "T5"}:
        row["automatic_content_eligible"] = False
        row["automatic_evidence_promotion"] = False
    return row


def dump(name: str, sources: list, header: str) -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    payload = {
        "schema": "source_registry_file.v1",
        "file": name,
        "notes": header,
        "sources": sources,
    }
    path = OUT / name
    path.write_text(
        yaml.safe_dump(payload, sort_keys=False, allow_unicode=True),
        encoding="utf-8",
    )
    print(f"wrote {path} ({len(sources)} sources)")


def main() -> None:
    dump(
        "current_collection.yaml",
        [
            src(id="hnrss_frontpage", name="Hacker News Frontpage RSS", publisher="HN RSS",
                homepage="https://hnrss.org/", adapter="rss",
                endpoints=["https://hnrss.org/frontpage"],
                topics=["open_source", "technology"], tier="T3",
                source_kind="aggregator", permitted_use="discovery_only",
                feeds_topic="General News & Research", feeds_key="rss_sources", enabled=True),
            src(id="the_verge", name="The Verge", publisher="Vox Media",
                homepage="https://www.theverge.com/", adapter="rss",
                endpoints=["https://www.theverge.com/rss/index.xml"],
                topics=["technology"], tier="T3", source_kind="newsroom",
                permitted_use="discovery_only",
                feeds_topic="General News & Research", feeds_key="rss_sources", enabled=True),
            src(id="techcrunch", name="TechCrunch", publisher="TechCrunch",
                homepage="https://techcrunch.com/", adapter="rss",
                endpoints=["https://techcrunch.com/feed/"],
                topics=["startups", "venture"], tier="T3", source_kind="newsroom",
                permitted_use="discovery_only",
                feeds_topic="General News & Research", feeds_key="rss_sources", enabled=True),
            src(id="wired", name="Wired", publisher="Condé Nast",
                homepage="https://www.wired.com/", adapter="rss",
                endpoints=["https://www.wired.com/feed/rss"],
                topics=["technology"], tier="T3", source_kind="newsroom",
                permitted_use="discovery_only",
                feeds_topic="General News & Research", feeds_key="rss_sources", enabled=True),
            src(id="ars_technica", name="Ars Technica", publisher="Condé Nast",
                homepage="https://arstechnica.com/", adapter="rss",
                endpoints=["https://arstechnica.com/feed/"],
                topics=["technology"], tier="T2", source_kind="specialist_newsroom",
                permitted_use="discovery_and_interpretation",
                feeds_topic="General News & Research", feeds_key="rss_sources", enabled=True),
            src(id="github_trending_typescript", name="GitHub Trending TypeScript",
                publisher="GitHub", homepage="https://github.com/trending/typescript",
                adapter="github_trending", endpoints=["typescript"],
                topics=["open_source"], tier="T3", source_kind="code_index",
                permitted_use="discovery_only",
                feeds_topic="General News & Research", feeds_key="github_sources", enabled=True),
            src(id="github_trending_python", name="GitHub Trending Python",
                publisher="GitHub", homepage="https://github.com/trending/python",
                adapter="github_trending", endpoints=["python"],
                topics=["open_source"], tier="T3", source_kind="code_index",
                permitted_use="discovery_only",
                feeds_topic="General News & Research", feeds_key="github_sources", enabled=True),
            src(id="github_trending_rust", name="GitHub Trending Rust",
                publisher="GitHub", homepage="https://github.com/trending/rust",
                adapter="github_trending", endpoints=["rust"],
                topics=["open_source"], tier="T3", source_kind="code_index",
                permitted_use="discovery_only",
                feeds_topic="General News & Research", feeds_key="github_sources", enabled=True),
            src(id="hn_open_source", name="Hacker News open source", publisher="Y Combinator",
                homepage="https://news.ycombinator.com/", adapter="hackernews",
                endpoints=["open source"], topics=["open_source"], tier="T3",
                source_kind="community_index", permitted_use="discovery_only",
                feeds_topic="General News & Research", feeds_key="hackernews_sources", enabled=True),
            src(id="hn_startup_funding", name="Hacker News startup funding", publisher="Y Combinator",
                homepage="https://news.ycombinator.com/", adapter="hackernews",
                endpoints=["startup funding"], topics=["startups"], tier="T3",
                source_kind="community_index", permitted_use="discovery_only",
                feeds_topic="General News & Research", feeds_key="hackernews_sources", enabled=True),
            src(id="hn_developer_tools", name="Hacker News developer tools", publisher="Y Combinator",
                homepage="https://news.ycombinator.com/", adapter="hackernews",
                endpoints=["developer tools"], topics=["developer_tools"], tier="T3",
                source_kind="community_index", permitted_use="discovery_only",
                feeds_topic="General News & Research", feeds_key="hackernews_sources", enabled=True),
            src(id="hn_tech_industry", name="Hacker News tech industry", publisher="Y Combinator",
                homepage="https://news.ycombinator.com/", adapter="hackernews",
                endpoints=["tech industry"], topics=["technology"], tier="T3",
                source_kind="community_index", permitted_use="discovery_only",
                feeds_topic="General News & Research", feeds_key="hackernews_sources", enabled=True),
            src(id="yt_fireship", name="Fireship", publisher="Fireship",
                homepage="https://www.youtube.com/@Fireship", adapter="youtube",
                endpoints=["@Fireship"], topics=["developer_tools"], tier="T4",
                source_kind="commentary", permitted_use="discovery_only",
                feeds_topic="General News & Research", feeds_key="youtube_sources", enabled=True),
            src(id="yt_primeagen", name="The Primeagen", publisher="The Primeagen",
                homepage="https://www.youtube.com/@ThePrimeTimeagen", adapter="youtube",
                endpoints=["@ThePrimeTimeagen"], topics=["developer_tools"], tier="T4",
                source_kind="commentary", permitted_use="discovery_only",
                feeds_topic="General News & Research", feeds_key="youtube_sources", enabled=True),
            src(id="yt_t3dotgg", name="Theo - t3.gg", publisher="Theo",
                homepage="https://www.youtube.com/@t3dotgg", adapter="youtube",
                endpoints=["@t3dotgg"], topics=["developer_tools"], tier="T4",
                source_kind="commentary", permitted_use="discovery_only",
                feeds_topic="General News & Research", feeds_key="youtube_sources", enabled=True),
            src(id="google_ai_blog", name="Google AI Blog", publisher="Google",
                homepage="https://blog.google/technology/ai/", adapter="rss",
                endpoints=["https://blog.google/technology/ai/rss/"],
                topics=["ai"], tier="T1", source_kind="official_lab",
                permitted_use="factual_support",
                feeds_topic="AI / AI Tools / AI Agents", feeds_key="rss_sources", enabled=True),
            src(id="huggingface_blog", name="Hugging Face Blog", publisher="Hugging Face",
                homepage="https://huggingface.co/blog", adapter="rss",
                endpoints=["https://huggingface.co/blog/feed.xml"],
                topics=["ai"], tier="T1", source_kind="official_lab",
                permitted_use="factual_support",
                feeds_topic="AI / AI Tools / AI Agents", feeds_key="rss_sources", enabled=True),
            src(id="marktechpost", name="MarkTechPost", publisher="MarkTechPost",
                homepage="https://www.marktechpost.com/", adapter="rss",
                endpoints=["https://www.marktechpost.com/feed/"],
                topics=["ai"], tier="T4", source_kind="aggregator",
                permitted_use="discovery_only",
                feeds_topic="AI / AI Tools / AI Agents", feeds_key="rss_sources", enabled=True,
                notes="Demoted to T4 discovery; do not treat as primary AI evidence."),
            src(id="ai_news_ainews", name="Artificial Intelligence News",
                publisher="AI News", homepage="https://www.artificialintelligence-news.com/",
                adapter="rss", endpoints=["https://www.artificialintelligence-news.com/feed/"],
                topics=["ai"], tier="T4", source_kind="aggregator",
                permitted_use="discovery_only",
                feeds_topic="AI / AI Tools / AI Agents", feeds_key="rss_sources", enabled=True),
            src(id="rundown_ai", name="The Rundown AI", publisher="The Rundown",
                homepage="https://www.rundown.ai/", adapter="rss",
                endpoints=["https://www.rundown.ai/rss"],
                topics=["ai"], tier="T4", source_kind="newsletter_aggregator",
                permitted_use="discovery_only",
                feeds_topic="AI / AI Tools / AI Agents", feeds_key="rss_sources", enabled=True),
            src(id="marktechpost_agents", name="AI Agent News", publisher="MarkTechPost",
                homepage="https://aiagent.marktechpost.com/", adapter="rss",
                endpoints=["https://aiagent.marktechpost.com/feed/"],
                topics=["ai_agents"], tier="T4", source_kind="aggregator",
                permitted_use="discovery_only",
                feeds_topic="AI / AI Tools / AI Agents", feeds_key="rss_sources", enabled=True),
            src(id="github_trending_python_ai", name="GitHub Trending Python (AI bucket)",
                publisher="GitHub", homepage="https://github.com/trending/python",
                adapter="github_trending", endpoints=["python"],
                topics=["ai"], tier="T3", source_kind="code_index",
                permitted_use="discovery_only",
                feeds_topic="AI / AI Tools / AI Agents", feeds_key="github_sources", enabled=True),
            src(id="hn_ai_agent", name="Hacker News AI agent", publisher="Y Combinator",
                homepage="https://news.ycombinator.com/", adapter="hackernews",
                endpoints=["AI agent"], topics=["ai_agents"], tier="T3",
                source_kind="community_index", permitted_use="discovery_only",
                feeds_topic="AI / AI Tools / AI Agents", feeds_key="hackernews_sources", enabled=True),
            src(id="hn_llm", name="Hacker News LLM", publisher="Y Combinator",
                homepage="https://news.ycombinator.com/", adapter="hackernews",
                endpoints=["LLM"], topics=["ai"], tier="T3",
                source_kind="community_index", permitted_use="discovery_only",
                feeds_topic="AI / AI Tools / AI Agents", feeds_key="hackernews_sources", enabled=True),
            src(id="hn_gpt", name="Hacker News GPT", publisher="Y Combinator",
                homepage="https://news.ycombinator.com/", adapter="hackernews",
                endpoints=["GPT"], topics=["ai"], tier="T3",
                source_kind="community_index", permitted_use="discovery_only",
                feeds_topic="AI / AI Tools / AI Agents", feeds_key="hackernews_sources", enabled=True),
            src(id="hn_machine_learning", name="Hacker News machine learning", publisher="Y Combinator",
                homepage="https://news.ycombinator.com/", adapter="hackernews",
                endpoints=["machine learning"], topics=["ai"], tier="T3",
                source_kind="community_index", permitted_use="discovery_only",
                feeds_topic="AI / AI Tools / AI Agents", feeds_key="hackernews_sources", enabled=True),
            *[
                src(id=sid, name=name, publisher=name, homepage=f"https://www.youtube.com/{handle}",
                    adapter="youtube", endpoints=[handle], topics=["ai"], tier="T4",
                    source_kind="commentary", permitted_use="discovery_only",
                    feeds_topic="AI / AI Tools / AI Agents", feeds_key="youtube_sources", enabled=True)
                for sid, name, handle in [
                    ("yt_two_minute_papers", "Two Minute Papers", "@TwoMinutePapers"),
                    ("yt_wes_roth", "Wes Roth", "@mreflow"),
                    ("yt_nate_herk", "Nate Herk", "@NateHerk"),
                    ("yt_ai_explained", "AI Explained", "@AIExplained"),
                    ("yt_indydevdan", "indydevdan", "indydevdan"),
                    ("yt_arseny_shatokhin", "Arseny Shatokhin", "UC_x36zCEGilGpB1m-V4gmjg"),
                    ("yt_matthew_berman", "Matthew Berman", "UCSv4qL8vmoSH7GaPjuqRiCQ"),
                    ("yt_worldofai", "WorldofAI", "UCawZsQWqfGSbCI5yjkdVkTA"),
                    ("yt_matt_wolfe", "Matt Wolfe", "UC2WmuBuFq6gL08QYG-JjXKw"),
                    ("yt_ai_channel_extra", "Additional AI channel", "UCAl9Ld79qaZxp9JzEOwd3aA"),
                ]
            ],
            src(id="coindesk", name="CoinDesk", publisher="CoinDesk",
                homepage="https://www.coindesk.com/", adapter="rss",
                endpoints=["https://www.coindesk.com/arc/outboundfeeds/rss/?outputType=xml"],
                topics=["crypto"], tier="T3", source_kind="newsroom",
                permitted_use="discovery_only",
                feeds_topic="Blockchain / Crypto / Web3", feeds_key="rss_sources", enabled=True),
            src(id="cointelegraph", name="Cointelegraph", publisher="Cointelegraph",
                homepage="https://cointelegraph.com/", adapter="rss",
                endpoints=["https://cointelegraph.com/rss"],
                topics=["crypto"], tier="T4", source_kind="newsroom",
                permitted_use="discovery_only",
                feeds_topic="Blockchain / Crypto / Web3", feeds_key="rss_sources", enabled=True,
                notes="Demoted to T4 promotional/interpretation discovery."),
            src(id="dailycoin", name="DailyCoin", publisher="DailyCoin",
                homepage="https://dailycoin.com/", adapter="rss",
                endpoints=["https://dailycoin.com/feed/"],
                topics=["crypto"], tier="T4", source_kind="newsroom",
                permitted_use="discovery_only",
                feeds_topic="Blockchain / Crypto / Web3", feeds_key="rss_sources", enabled=True),
            src(id="bankless_rss", name="Bankless", publisher="Bankless",
                homepage="https://www.bankless.com/", adapter="rss",
                endpoints=["https://www.bankless.com/feed"],
                topics=["crypto"], tier="T3", source_kind="commentary",
                permitted_use="discovery_only",
                feeds_topic="Blockchain / Crypto / Web3", feeds_key="rss_sources", enabled=True),
            src(id="blockchain_app_factory", name="Blockchain App Factory",
                publisher="Blockchain App Factory",
                homepage="https://www.blockchainappfactory.com/", adapter="rss",
                endpoints=["https://www.blockchainappfactory.com/blog/feed/"],
                topics=["crypto"], tier="T4", source_kind="promotional",
                permitted_use="discovery_only",
                feeds_topic="Blockchain / Crypto / Web3", feeds_key="rss_sources", enabled=True),
            src(id="github_trending_solana", name="GitHub Trending Solana",
                publisher="GitHub", homepage="https://github.com/trending/solana",
                adapter="github_trending", endpoints=["solana"],
                topics=["crypto"], tier="T3", source_kind="code_index",
                permitted_use="discovery_only",
                feeds_topic="Blockchain / Crypto / Web3", feeds_key="github_sources", enabled=True),
            src(id="hn_crypto_funding", name="Hacker News crypto funding", publisher="Y Combinator",
                homepage="https://news.ycombinator.com/", adapter="hackernews",
                endpoints=["crypto funding"], topics=["crypto"], tier="T3",
                source_kind="community_index", permitted_use="discovery_only",
                feeds_topic="Blockchain / Crypto / Web3", feeds_key="hackernews_sources", enabled=True),
            src(id="hn_blockchain_funding", name="Hacker News blockchain funding", publisher="Y Combinator",
                homepage="https://news.ycombinator.com/", adapter="hackernews",
                endpoints=["blockchain funding"], topics=["crypto"], tier="T3",
                source_kind="community_index", permitted_use="discovery_only",
                feeds_topic="Blockchain / Crypto / Web3", feeds_key="hackernews_sources", enabled=True),
            src(id="hn_web3", name="Hacker News web3", publisher="Y Combinator",
                homepage="https://news.ycombinator.com/", adapter="hackernews",
                endpoints=["web3"], topics=["crypto"], tier="T3",
                source_kind="community_index", permitted_use="discovery_only",
                feeds_topic="Blockchain / Crypto / Web3", feeds_key="hackernews_sources", enabled=True),
            src(id="hn_tokenization", name="Hacker News tokenization", publisher="Y Combinator",
                homepage="https://news.ycombinator.com/", adapter="hackernews",
                endpoints=["tokenization"], topics=["tokenization"], tier="T3",
                source_kind="community_index", permitted_use="discovery_only",
                feeds_topic="Blockchain / Crypto / Web3", feeds_key="hackernews_sources", enabled=True),
            *[
                src(id=sid, name=name, publisher=name, homepage=f"https://www.youtube.com/{handle}",
                    adapter="youtube", endpoints=[handle], topics=["crypto"], tier="T4",
                    source_kind="commentary", permitted_use="discovery_only",
                    feeds_topic="Blockchain / Crypto / Web3", feeds_key="youtube_sources", enabled=True)
                for sid, name, handle in [
                    ("yt_coinbureau", "Coin Bureau", "@CoinBureau"),
                    ("yt_bankless", "Bankless", "@Bankless"),
                    ("yt_ivan_on_tech", "Ivan on Tech", "@IvanOnTech"),
                    ("yt_bitboy_legacy", "BitBoy X legacy id", "UChpleBmo18P08aKCIgti38g"),
                    ("yt_coinbureau_id", "Coin Bureau channel id", "UCuV9EB4I9L-xmRoaXd8tmuA"),
                    ("yt_bankless_id", "Bankless channel id", "UCqK_GSMbpiV8spgD3ZGloSw"),
                ]
            ],
            src(id="bbc_tech", name="BBC Technology", publisher="BBC",
                homepage="https://www.bbc.co.uk/news/technology", adapter="rss",
                endpoints=["https://www.bbc.co.uk/news/technology/rss.xml"],
                topics=["technology", "geopolitics"], tier="T3", source_kind="newsroom",
                permitted_use="discovery_only",
                feeds_topic="Sense-Making & Narrative Analysis", feeds_key="rss_sources", enabled=True),
            src(id="reuters_rss", name="Reuters", publisher="Reuters",
                homepage="https://www.reuters.com/", adapter="rss",
                endpoints=["https://www.reuters.com/arc/outboundfeeds/v3/all/rss.xml"],
                topics=["geopolitics", "markets"], tier="T3", source_kind="newsroom",
                permitted_use="discovery_only",
                feeds_topic="Sense-Making & Narrative Analysis", feeds_key="rss_sources", enabled=True),
            src(id="lesswrong", name="LessWrong", publisher="LessWrong",
                homepage="https://www.lesswrong.com/", adapter="rss",
                endpoints=["https://www.lesswrong.com/feed.xml"],
                topics=["epistemics"], tier="T3", source_kind="essay",
                permitted_use="discovery_and_interpretation",
                feeds_topic="Sense-Making & Narrative Analysis", feeds_key="rss_sources", enabled=True),
            src(id="astral_codex_ten", name="Astral Codex Ten", publisher="Scott Alexander",
                homepage="https://www.astralcodexten.com/", adapter="rss",
                endpoints=["https://www.astralcodexten.com/feed"],
                topics=["epistemics"], tier="T3", source_kind="essay",
                permitted_use="discovery_and_interpretation",
                feeds_topic="Sense-Making & Narrative Analysis", feeds_key="rss_sources", enabled=True),
            src(id="foreign_affairs", name="Foreign Affairs", publisher="CFR",
                homepage="https://www.foreignaffairs.com/", adapter="rss",
                endpoints=["https://www.foreignaffairs.com/rss.xml"],
                topics=["geopolitics"], tier="T2", source_kind="journal",
                permitted_use="discovery_and_interpretation",
                feeds_topic="Sense-Making & Narrative Analysis", feeds_key="rss_sources", enabled=True),
            src(id="hn_geopolitics", name="Hacker News geopolitics", publisher="Y Combinator",
                homepage="https://news.ycombinator.com/", adapter="hackernews",
                endpoints=["geopolitics"], topics=["geopolitics"], tier="T3",
                source_kind="community_index", permitted_use="discovery_only",
                feeds_topic="Sense-Making & Narrative Analysis", feeds_key="hackernews_sources", enabled=True),
            src(id="hn_misinformation", name="Hacker News misinformation", publisher="Y Combinator",
                homepage="https://news.ycombinator.com/", adapter="hackernews",
                endpoints=["misinformation"], topics=["media"], tier="T3",
                source_kind="community_index", permitted_use="discovery_only",
                feeds_topic="Sense-Making & Narrative Analysis", feeds_key="hackernews_sources", enabled=True),
            src(id="hn_media_analysis", name="Hacker News media analysis", publisher="Y Combinator",
                homepage="https://news.ycombinator.com/", adapter="hackernews",
                endpoints=["media analysis"], topics=["media"], tier="T3",
                source_kind="community_index", permitted_use="discovery_only",
                feeds_topic="Sense-Making & Narrative Analysis", feeds_key="hackernews_sources", enabled=True),
            src(id="hn_institutional", name="Hacker News institutional", publisher="Y Combinator",
                homepage="https://news.ycombinator.com/", adapter="hackernews",
                endpoints=["institutional"], topics=["institutions"], tier="T3",
                source_kind="community_index", permitted_use="discovery_only",
                feeds_topic="Sense-Making & Narrative Analysis", feeds_key="hackernews_sources", enabled=True),
            *[
                src(id=sid, name=name, publisher=name, homepage=f"https://www.youtube.com/{handle}",
                    adapter="youtube", endpoints=[handle], topics=["geopolitics"], tier="T4",
                    source_kind="commentary", permitted_use="discovery_only",
                    feeds_topic="Sense-Making & Narrative Analysis", feeds_key="youtube_sources", enabled=True)
                for sid, name, handle in [
                    ("yt_all_in_podcast", "All-In Podcast", "@AllInPodcast"),
                    ("yt_lex_fridman", "Lex Fridman", "@LexFridman"),
                    ("yt_johnny_harris_sm", "Johnny Harris", "@JohnnyHarris"),
                    ("yt_bloomberg_tv", "Bloomberg Television", "@BloombergTelevision"),
                    ("yt_visual_capitalist", "Visual Capitalist", "@VisualCapitalist"),
                ]
            ],
            *[
                src(id=sid, name=name, publisher=name, homepage=f"https://www.youtube.com/{handle}",
                    adapter="youtube", endpoints=[handle], topics=["investigations"],
                    tier="T4", source_kind="commentary", permitted_use="discovery_only",
                    feeds_topic="Alternative News & Independent Commentary",
                    feeds_key="youtube_sources", enabled=True)
                for sid, name, handle in [
                    ("yt_coffeezilla", "Coffeezilla", "@Coffeezilla"),
                    ("yt_breaking_points", "Breaking Points", "@breakingpoints"),
                    ("yt_nick_shirley", "Nick Shirley", "@NickShirley"),
                    ("yt_johnny_harris_alt", "Johnny Harris alt", "@johnnyharris"),
                    ("yt_tldr_podcasts", "TLDR podcasts", "@tldrpodcasts"),
                    ("yt_the_independent", "The Independent", "theindependent"),
                    ("yt_diary_of_a_ceo", "The Diary Of A CEO", "@TheDiaryOfACEO"),
                ]
            ],
            src(id="pubmed_peptides_wellness", name="PubMed peptides wellness",
                publisher="NCBI", homepage="https://pubmed.ncbi.nlm.nih.gov/",
                adapter="pubmed",
                endpoints=["(peptides[Title/Abstract] OR peptide therapeutics[Title/Abstract]) AND wellness"],
                topics=["peptides"], tier="T0", source_kind="research_database",
                permitted_use="factual_support",
                feeds_topic="Peptides / Wellness / Longevity", feeds_key="pubmed_sources", enabled=True),
            src(id="pubmed_bpc157", name="PubMed BPC-157", publisher="NCBI",
                homepage="https://pubmed.ncbi.nlm.nih.gov/", adapter="pubmed",
                endpoints=["BPC-157 peptide"], topics=["peptides"], tier="T0",
                source_kind="research_database", permitted_use="factual_support",
                feeds_topic="Peptides / Wellness / Longevity", feeds_key="pubmed_sources", enabled=True),
            src(id="pubmed_ghkcu", name="PubMed GHK-Cu", publisher="NCBI",
                homepage="https://pubmed.ncbi.nlm.nih.gov/", adapter="pubmed",
                endpoints=["GHK-Cu peptide"], topics=["peptides"], tier="T0",
                source_kind="research_database", permitted_use="factual_support",
                feeds_topic="Peptides / Wellness / Longevity", feeds_key="pubmed_sources", enabled=True),
            src(id="pubmed_kpv", name="PubMed KPV", publisher="NCBI",
                homepage="https://pubmed.ncbi.nlm.nih.gov/", adapter="pubmed",
                endpoints=["KPV peptide"], topics=["peptides"], tier="T0",
                source_kind="research_database", permitted_use="factual_support",
                feeds_topic="Peptides / Wellness / Longevity", feeds_key="pubmed_sources", enabled=True),
            src(id="pubmed_nad", name="PubMed NAD+", publisher="NCBI",
                homepage="https://pubmed.ncbi.nlm.nih.gov/", adapter="pubmed",
                endpoints=["NAD+ peptide"], topics=["peptides"], tier="T0",
                source_kind="research_database", permitted_use="factual_support",
                feeds_topic="Peptides / Wellness / Longevity", feeds_key="pubmed_sources", enabled=True),
            src(id="pubmed_glp1", name="PubMed GLP-1", publisher="NCBI",
                homepage="https://pubmed.ncbi.nlm.nih.gov/", adapter="pubmed",
                endpoints=["GLP-1 peptide"], topics=["peptides"], tier="T0",
                source_kind="research_database", permitted_use="factual_support",
                feeds_topic="Peptides / Wellness / Longevity", feeds_key="pubmed_sources", enabled=True),
            src(id="pubmed_collagen", name="PubMed collagen peptides", publisher="NCBI",
                homepage="https://pubmed.ncbi.nlm.nih.gov/", adapter="pubmed",
                endpoints=["collagen peptides"], topics=["peptides"], tier="T0",
                source_kind="research_database", permitted_use="factual_support",
                feeds_topic="Peptides / Wellness / Longevity", feeds_key="pubmed_sources", enabled=True),
            src(id="pubmed_thymosin", name="PubMed thymosin alpha-1", publisher="NCBI",
                homepage="https://pubmed.ncbi.nlm.nih.gov/", adapter="pubmed",
                endpoints=["thymosin alpha-1 peptide"], topics=["peptides"], tier="T0",
                source_kind="research_database", permitted_use="factual_support",
                feeds_topic="Peptides / Wellness / Longevity", feeds_key="pubmed_sources", enabled=True),
            *[
                src(id=sid, name=name, publisher="ClinicalTrials.gov",
                    homepage="https://clinicaltrials.gov/", adapter="clinical_trials",
                    endpoints=[query], topics=["peptides"], tier="T0",
                    source_kind="clinical_trial_registry", permitted_use="factual_support",
                    feeds_topic="Peptides / Wellness / Longevity",
                    feeds_key="clinical_trials_sources", enabled=True)
                for sid, name, query in [
                    ("ct_peptide_therapy", "ClinicalTrials peptide therapy", "peptide therapy"),
                    ("ct_bpc157", "ClinicalTrials BPC-157", "BPC-157"),
                    ("ct_ghkcu", "ClinicalTrials GHK-Cu", "GHK-Cu"),
                    ("ct_nad", "ClinicalTrials NAD+", "NAD+"),
                    ("ct_glp1", "ClinicalTrials GLP-1", "GLP-1"),
                    ("ct_collagen", "ClinicalTrials collagen peptides", "collagen peptides"),
                    ("ct_semaglutide", "ClinicalTrials semaglutide", "semaglutide peptide"),
                    ("ct_tirzepatide", "ClinicalTrials tirzepatide", "tirzepatide"),
                    ("ct_retatrutide", "ClinicalTrials retatrutide", "retatrutide"),
                ]
            ],
            src(id="hn_peptides", name="Hacker News peptides", publisher="Y Combinator",
                homepage="https://news.ycombinator.com/", adapter="hackernews",
                endpoints=["peptides"], topics=["peptides"], tier="T3",
                source_kind="community_index", permitted_use="discovery_only",
                feeds_topic="Peptides / Wellness / Longevity", feeds_key="hackernews_sources", enabled=True),
            src(id="hn_glp1", name="Hacker News GLP-1", publisher="Y Combinator",
                homepage="https://news.ycombinator.com/", adapter="hackernews",
                endpoints=["GLP-1"], topics=["peptides"], tier="T3",
                source_kind="community_index", permitted_use="discovery_only",
                feeds_topic="Peptides / Wellness / Longevity", feeds_key="hackernews_sources", enabled=True),
            src(id="hn_longevity", name="Hacker News longevity", publisher="Y Combinator",
                homepage="https://news.ycombinator.com/", adapter="hackernews",
                endpoints=["longevity"], topics=["longevity"], tier="T3",
                source_kind="community_index", permitted_use="discovery_only",
                feeds_topic="Peptides / Wellness / Longevity", feeds_key="hackernews_sources", enabled=True),
            src(id="hn_fda_peptide", name="Hacker News FDA peptide", publisher="Y Combinator",
                homepage="https://news.ycombinator.com/", adapter="hackernews",
                endpoints=["FDA peptide"], topics=["peptides"], tier="T3",
                source_kind="community_index", permitted_use="discovery_only",
                feeds_topic="Peptides / Wellness / Longevity", feeds_key="hackernews_sources", enabled=True),
            src(id="eric_topol_ground_truths", name="Ground Truths / Eric Topol",
                publisher="Eric Topol", homepage="https://erictopol.substack.com/",
                adapter="rss", endpoints=["https://erictopol.substack.com/feed"],
                topics=["health"], tier="T2", source_kind="expert_interpretation",
                permitted_use="discovery_and_interpretation",
                feeds_topic="Peptides / Wellness / Longevity", feeds_key="rss_sources", enabled=True),
            *[
                src(id=sid, name=name, publisher=name, homepage="https://www.youtube.com/",
                    adapter="youtube", endpoints=[query], topics=["peptides"], tier="T4",
                    source_kind="trend_listening", permitted_use="discovery_only",
                    feeds_topic="Peptides / Wellness / Longevity",
                    feeds_key="youtube_sources", enabled=True,
                    notes="Trend/listening query only; never a medical evidence source.")
                for sid, name, query in [
                    ("yt_ben_greenfield_peptides", "Ben Greenfield peptides", "Ben Greenfield peptides"),
                    ("yt_dave_asprey_peptides", "Dave Asprey peptides", "Dave Asprey peptides"),
                    ("yt_peptides_physician", "peptides physician lecture", "peptides physician lecture"),
                    ("yt_glp1_science", "GLP-1 peptide science", "GLP-1 peptide science"),
                ]
            ],
        ],
        "Migrated current feeds.yaml entries with explicit tiers. Aggregators demoted to T3/T4.",
    )

    dump(
        "global_events.yaml",
        [
            src(id="reliefweb_updates", name="ReliefWeb Updates", publisher="UN OCHA",
                homepage="https://reliefweb.int/", adapter="rss",
                endpoints=["https://reliefweb.int/updates/rss.xml"],
                topics=["humanitarian", "global_events"], regions=["global"],
                tier="T0", source_kind="humanitarian_index", permitted_use="factual_support",
                license_or_terms_url="https://reliefweb.int/terms-and-conditions",
                feeds_topic="Official Records & Primary Sources", feeds_key="rss_sources", enabled=True),
            src(id="gdacs_rss", name="GDACS", publisher="European Commission / UN",
                homepage="https://www.gdacs.org/", adapter="rss",
                endpoints=["https://www.gdacs.org/xml/rss.xml"],
                topics=["disasters", "global_events"], tier="T0",
                source_kind="geoevent", permitted_use="factual_support",
                license_or_terms_url="https://www.gdacs.org/",
                feeds_topic="Official Records & Primary Sources", feeds_key="rss_sources", enabled=True),
            src(id="usgs_significant_week", name="USGS significant earthquakes",
                publisher="U.S. Geological Survey",
                homepage="https://earthquake.usgs.gov/", adapter="rss",
                endpoints=["https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/significant_week.atom"],
                topics=["earthquakes", "geospatial"], regions=["US", "global"],
                tier="T0", source_kind="scientific_agency", permitted_use="factual_support",
                license_or_terms_url="https://www.usgs.gov/information-policies-and-instructions",
                feeds_topic="Official Records & Primary Sources", feeds_key="rss_sources", enabled=True),
            src(id="un_news", name="UN News", publisher="United Nations",
                homepage="https://news.un.org/", adapter="rss",
                endpoints=["https://news.un.org/feed/subscribe/en/news/all/rss.xml"],
                topics=["global_events", "diplomacy"], tier="T1",
                source_kind="intergovernmental", permitted_use="factual_support",
                feeds_topic="Official Records & Primary Sources", feeds_key="rss_sources", enabled=True),
            src(id="nasa_eonet", name="NASA EONET", publisher="NASA",
                homepage="https://eonet.gsfc.nasa.gov/", adapter="json_api",
                endpoints=["https://eonet.gsfc.nasa.gov/api/v3/events"],
                topics=["earth_observation"], tier="T0", source_kind="scientific_agency",
                permitted_use="factual_support",
                disabled_reason="json_api adapter is not wired into daily_run yet",
                license_or_terms_url="https://earthdata.nasa.gov/earth-observation-data/near-real-time/eonet"),
            src(id="earth_observatory", name="NASA Earth Observatory", publisher="NASA",
                homepage="https://earthobservatory.nasa.gov/", adapter="rss",
                endpoints=["https://earthobservatory.nasa.gov/feeds/earth-observatory.rss"],
                topics=["earth_observation"], tier="T1", source_kind="scientific_agency",
                permitted_use="factual_support",
                feeds_topic="Official Records & Primary Sources", feeds_key="rss_sources", enabled=True),
        ],
        "Wave A global event and geospatial primary sources.",
    )

    dump(
        "macro_markets.yaml",
        [
            src(id="federal_reserve_press", name="Federal Reserve press",
                publisher="Board of Governors of the Federal Reserve System",
                homepage="https://www.federalreserve.gov/", adapter="rss",
                endpoints=["https://www.federalreserve.gov/feeds/press_all.xml"],
                topics=["macro", "markets"], regions=["US"], tier="T0",
                source_kind="central_bank", permitted_use="factual_support",
                license_or_terms_url="https://www.federalreserve.gov/website-policies.htm",
                feeds_topic="Official Records & Primary Sources", feeds_key="rss_sources", enabled=True),
            src(id="us_treasury_rss", name="U.S. Treasury RSS",
                publisher="U.S. Department of the Treasury",
                homepage="https://home.treasury.gov/", adapter="rss",
                endpoints=["https://home.treasury.gov/rss.xml"],
                topics=["macro", "fiscal"], regions=["US"], tier="T0",
                source_kind="finance_ministry", permitted_use="factual_support",
                feeds_topic="Official Records & Primary Sources", feeds_key="rss_sources", enabled=True),
            src(id="bis_all", name="Bank for International Settlements",
                publisher="BIS", homepage="https://www.bis.org/", adapter="rss",
                endpoints=["https://www.bis.org/doclist/rss_all_categories.rss"],
                topics=["macro", "tokenization", "regulation"], tier="T0",
                source_kind="intergovernmental", permitted_use="factual_support",
                feeds_topic="Official Records & Primary Sources", feeds_key="rss_sources", enabled=True),
            src(id="fred_blog", name="FRED Blog", publisher="Federal Reserve Bank of St. Louis",
                homepage="https://fredblog.stlouisfed.org/", adapter="rss",
                endpoints=["https://fredblog.stlouisfed.org/feed/"],
                topics=["macro", "data"], regions=["US"], tier="T1",
                source_kind="statistical_commentary", permitted_use="factual_support",
                feeds_topic="Official Records & Primary Sources", feeds_key="rss_sources", enabled=True),
            src(id="bls_latest", name="U.S. Bureau of Labor Statistics",
                publisher="BLS", homepage="https://www.bls.gov/", adapter="rss",
                endpoints=["https://www.bls.gov/feed/bls_latest.rss"],
                topics=["macro", "labor"], regions=["US"], tier="T0",
                source_kind="statistical_agency", permitted_use="factual_support",
                disabled_reason="Feed returned HTTP 403 during 2026-08-15 endpoint verification"),
            src(id="bea_news", name="U.S. Bureau of Economic Analysis",
                publisher="BEA", homepage="https://www.bea.gov/", adapter="site_change",
                endpoints=["https://www.bea.gov/news/releases"],
                topics=["macro"], regions=["US"], tier="T0",
                source_kind="statistical_agency", permitted_use="factual_support",
                license_or_terms_url="https://www.bea.gov/about/policies-and-notices",
                disabled_reason="No verified RSS; site_change adapter not in daily_run"),
            src(id="ecb_press", name="European Central Bank press",
                publisher="ECB", homepage="https://www.ecb.europa.eu/", adapter="rss",
                endpoints=["https://www.ecb.europa.eu/rss/press.html"],
                topics=["macro"], regions=["EU"], tier="T0",
                source_kind="central_bank", permitted_use="factual_support",
                disabled_reason="TLS verification failed from the audit host; re-check on Actions before enabling"),
            src(id="imf_news", name="IMF News", publisher="IMF",
                homepage="https://www.imf.org/", adapter="rss",
                endpoints=["https://www.imf.org/en/News/rss"],
                topics=["macro"], tier="T0", source_kind="intergovernmental",
                permitted_use="factual_support",
                disabled_reason="Feed returned HTTP 403 during endpoint verification"),
        ],
        "Wave A macro and official market sources.",
    )

    dump(
        "regulation_companies.yaml",
        [
            src(id="federal_register_articles", name="Federal Register articles",
                publisher="National Archives", homepage="https://www.federalregister.gov/",
                adapter="rss",
                endpoints=["https://www.federalregister.gov/api/v1/articles.rss"],
                topics=["regulation", "legal"], regions=["US"], tier="T0",
                source_kind="regulator_record", permitted_use="factual_support",
                license_or_terms_url="https://www.federalregister.gov/reader-aids/government-policy-and-ofr-procedures",
                feeds_topic="Official Records & Primary Sources", feeds_key="rss_sources", enabled=True),
            src(id="govinfo_federal_register", name="GovInfo Federal Register",
                publisher="U.S. Government Publishing Office",
                homepage="https://www.govinfo.gov/", adapter="rss",
                endpoints=["https://www.govinfo.gov/rss/fr.xml"],
                topics=["regulation"], regions=["US"], tier="T0",
                source_kind="regulator_record", permitted_use="factual_support",
                feeds_topic="Official Records & Primary Sources", feeds_key="rss_sources", enabled=True),
            src(id="sec_press", name="SEC press releases",
                publisher="U.S. Securities and Exchange Commission",
                homepage="https://www.sec.gov/", adapter="rss",
                endpoints=["https://www.sec.gov/news/pressreleases.rss"],
                topics=["markets", "companies", "tokenization", "legal"], regions=["US"],
                tier="T1", source_kind="regulator_news", permitted_use="factual_support",
                license_or_terms_url="https://www.sec.gov/os/accessing-edgar-data",
                feeds_topic="Official Records & Primary Sources", feeds_key="rss_sources", enabled=True),
            src(id="sec_edgar", name="SEC EDGAR submissions",
                publisher="U.S. Securities and Exchange Commission",
                homepage="https://www.sec.gov/search-filings", adapter="sec_edgar",
                endpoints=["https://data.sec.gov/submissions/"],
                topics=["markets", "companies", "tokenization", "legal"], regions=["US"],
                tier="T0", source_kind="regulator_record", permitted_use="factual_support",
                license_or_terms_url="https://www.sec.gov/os/accessing-edgar-data",
                disabled_reason="sec_edgar adapter is not wired into daily_run yet"),
            src(id="cftc_press", name="CFTC press", publisher="CFTC",
                homepage="https://www.cftc.gov/", adapter="rss",
                endpoints=["https://www.cftc.gov/RSS"],
                topics=["regulation", "markets"], regions=["US"], tier="T0",
                source_kind="regulator_record", permitted_use="factual_support",
                disabled_reason="TLS verification failed during endpoint check"),
            src(id="finra_news", name="FINRA news", publisher="FINRA",
                homepage="https://www.finra.org/", adapter="site_change",
                endpoints=["https://www.finra.org/media-center"],
                topics=["regulation"], regions=["US"], tier="T1",
                source_kind="sro_record", permitted_use="factual_support",
                license_or_terms_url="https://www.finra.org/legal-notices",
                disabled_reason="No verified RSS; site_change not in daily_run"),
            src(id="fincen_news", name="FinCEN", publisher="FinCEN",
                homepage="https://www.fincen.gov/", adapter="site_change",
                endpoints=["https://www.fincen.gov/news-room"],
                topics=["aml", "regulation"], regions=["US"], tier="T0",
                source_kind="regulator_record", permitted_use="factual_support",
                license_or_terms_url="https://www.fincen.gov/",
                disabled_reason="No verified public RSS; site_change not in daily_run"),
            src(id="ofac_updates", name="OFAC", publisher="U.S. Treasury OFAC",
                homepage="https://ofac.treasury.gov/", adapter="site_change",
                endpoints=["https://ofac.treasury.gov/recent-actions"],
                topics=["sanctions"], regions=["US"], tier="T0",
                source_kind="regulator_record", permitted_use="factual_support",
                license_or_terms_url="https://ofac.treasury.gov/",
                disabled_reason="No verified RSS; site_change not in daily_run"),
        ],
        "Wave A regulation and company-record sources.",
    )

    dump(
        "ai_agents.yaml",
        [
            src(id="arxiv_cs_ai", name="arXiv cs.AI", publisher="arXiv",
                homepage="https://arxiv.org/", adapter="rss",
                endpoints=["https://rss.arxiv.org/rss/cs.AI"],
                topics=["ai", "research"], tier="T0", source_kind="research_repository",
                permitted_use="factual_support",
                license_or_terms_url="https://info.arxiv.org/help/license/index.html",
                feeds_topic="Official Records & Primary Sources", feeds_key="rss_sources", enabled=True),
            src(id="openai_news", name="OpenAI news", publisher="OpenAI",
                homepage="https://openai.com/news/", adapter="rss",
                endpoints=["https://openai.com/news/rss.xml"],
                topics=["ai"], tier="T1", source_kind="official_lab",
                permitted_use="factual_support",
                feeds_topic="Official Records & Primary Sources", feeds_key="rss_sources", enabled=True),
            src(id="deepmind_blog", name="Google DeepMind blog", publisher="Google DeepMind",
                homepage="https://deepmind.google/blog/", adapter="rss",
                endpoints=["https://deepmind.google/blog/rss.xml"],
                topics=["ai"], tier="T1", source_kind="official_lab",
                permitted_use="factual_support",
                feeds_topic="Official Records & Primary Sources", feeds_key="rss_sources", enabled=True),
            src(id="github_blog", name="GitHub Blog", publisher="GitHub",
                homepage="https://github.blog/", adapter="rss",
                endpoints=["https://github.blog/feed/"],
                topics=["developer_tools", "ai"], tier="T1", source_kind="official_product",
                permitted_use="factual_support",
                feeds_topic="Official Records & Primary Sources", feeds_key="rss_sources", enabled=True),
            src(id="anthropic_news", name="Anthropic news", publisher="Anthropic",
                homepage="https://www.anthropic.com/news", adapter="site_change",
                endpoints=["https://www.anthropic.com/news"],
                topics=["ai"], tier="T1", source_kind="official_lab",
                permitted_use="factual_support",
                license_or_terms_url="https://www.anthropic.com/",
                disabled_reason="No verified RSS; site_change not in daily_run"),
            src(id="mistral_news", name="Mistral news", publisher="Mistral AI",
                homepage="https://mistral.ai/news/", adapter="site_change",
                endpoints=["https://mistral.ai/news/"],
                topics=["ai"], tier="T1", source_kind="official_lab",
                permitted_use="factual_support",
                license_or_terms_url="https://mistral.ai/",
                disabled_reason="No verified RSS; site_change not in daily_run"),
            src(id="meta_ai_blog", name="Meta AI blog", publisher="Meta",
                homepage="https://ai.meta.com/blog/", adapter="site_change",
                endpoints=["https://ai.meta.com/blog/"],
                topics=["ai"], tier="T1", source_kind="official_lab",
                permitted_use="factual_support",
                license_or_terms_url="https://ai.meta.com/",
                disabled_reason="RSS 404; site_change not in daily_run"),
        ],
        "Wave A official AI/research sources. Existing Hugging Face and Google AI live in current_collection.yaml.",
    )

    dump(
        "spatial_energy.yaml",
        [
            src(id="eia_today_in_energy", name="EIA Today in Energy",
                publisher="U.S. Energy Information Administration",
                homepage="https://www.eia.gov/", adapter="rss",
                endpoints=["https://www.eia.gov/rss/todayinenergy.xml"],
                topics=["energy"], regions=["US", "global"], tier="T0",
                source_kind="statistical_agency", permitted_use="factual_support",
                license_or_terms_url="https://www.eia.gov/about/copyrights_reuse.php",
                feeds_topic="Official Records & Primary Sources", feeds_key="rss_sources", enabled=True),
            src(id="nrel_news", name="NREL news", publisher="NREL",
                homepage="https://www.nrel.gov/", adapter="rss",
                endpoints=["https://www.nrel.gov/news/rss.xml"],
                topics=["energy"], regions=["US"], tier="T1",
                source_kind="national_lab", permitted_use="factual_support",
                disabled_reason="DNS lookup failed during 2026-08-15 verification"),
            src(id="doe_osti", name="DOE OSTI", publisher="U.S. Department of Energy",
                homepage="https://www.osti.gov/", adapter="site_change",
                endpoints=["https://www.osti.gov/"],
                topics=["energy", "research"], regions=["US"], tier="T1",
                source_kind="research_repository", permitted_use="factual_support",
                license_or_terms_url="https://www.osti.gov/disclaimer",
                disabled_reason="No verified RSS; site_change not in daily_run"),
            src(id="global_energy_monitor", name="Global Energy Monitor",
                publisher="Global Energy Monitor", homepage="https://globalenergymonitor.org/",
                adapter="site_change", endpoints=["https://globalenergymonitor.org/"],
                topics=["energy"], tier="T1", source_kind="project_database",
                permitted_use="documentary_lead",
                license_or_terms_url="https://globalenergymonitor.org/",
                disabled_reason="No verified RSS; site_change not in daily_run"),
        ],
        "Wave A energy and spatial primary sources.",
    )

    dump(
        "panama_latam.yaml",
        [
            src(id="gaceta_oficial_panama", name="Gaceta Oficial de Panamá",
                publisher="Gobierno de Panamá", homepage="https://www.gacetaoficial.gob.pa/",
                adapter="site_change", endpoints=["https://www.gacetaoficial.gob.pa/"],
                topics=["panama", "regulation"], regions=["PA"], languages=["es"],
                tier="T0", source_kind="official_gazette", permitted_use="factual_support",
                license_or_terms_url="https://www.gacetaoficial.gob.pa/",
                disabled_reason="No verified RSS; site_change not in daily_run"),
            src(id="panamacompra_ocds", name="PanamaCompra OCDS",
                publisher="PanamaCompra", homepage="https://www.panamacompra.gob.pa/",
                adapter="ocds", endpoints=["https://www.panamacompra.gob.pa/"],
                topics=["panama", "procurement"], regions=["PA"], languages=["es"],
                tier="T0", source_kind="procurement_record", permitted_use="factual_support",
                disabled_reason="ocds adapter is not wired into daily_run yet"),
            src(id="smv_panama", name="SMV Panamá",
                publisher="Superintendencia del Mercado de Valores",
                homepage="https://www.supervalores.gob.pa/", adapter="site_change",
                endpoints=["https://www.supervalores.gob.pa/"],
                topics=["panama", "markets"], regions=["PA"], languages=["es"],
                tier="T0", source_kind="securities_regulator", permitted_use="factual_support",
                license_or_terms_url="https://www.supervalores.gob.pa/",
                disabled_reason="No verified RSS; site_change not in daily_run"),
            src(id="sbp_panama", name="Superintendencia de Bancos de Panamá",
                publisher="SBP", homepage="https://www.superbancos.gob.pa/",
                adapter="site_change", endpoints=["https://www.superbancos.gob.pa/"],
                topics=["panama", "banking"], regions=["PA"], languages=["es"],
                tier="T0", source_kind="banking_regulator", permitted_use="factual_support",
                license_or_terms_url="https://www.superbancos.gob.pa/",
                disabled_reason="No verified RSS; site_change not in daily_run"),
            src(id="inec_panama", name="INEC Panamá",
                publisher="Instituto Nacional de Estadística y Censo",
                homepage="https://www.inec.gob.pa/", adapter="site_change",
                endpoints=["https://www.inec.gob.pa/"],
                topics=["panama", "statistics"], regions=["PA"], languages=["es"],
                tier="T0", source_kind="statistical_agency", permitted_use="factual_support",
                license_or_terms_url="https://www.inec.gob.pa/",
                disabled_reason="No verified RSS; site_change not in daily_run"),
            src(id="canal_de_panama", name="Canal de Panamá",
                publisher="Autoridad del Canal de Panamá",
                homepage="https://www.pancanal.com/", adapter="site_change",
                endpoints=["https://www.pancanal.com/"],
                topics=["panama", "logistics"], regions=["PA"], languages=["es", "en"],
                tier="T1", source_kind="infrastructure_operator", permitted_use="factual_support",
                license_or_terms_url="https://www.pancanal.com/",
                disabled_reason="No verified RSS; site_change not in daily_run"),
        ],
        "Panama official sources. Disabled until site/OCDS adapters are production-ready. No buyer or CRM data.",
    )

    dump(
        "investigative_documents.yaml",
        [
            src(id="unlimited_hangout_site", name="Unlimited Hangout",
                publisher="Unlimited Hangout", homepage="https://unlimitedhangout.com/",
                adapter="rss", endpoints=["https://unlimitedhangout.com/feed/"],
                topics=["investigations", "finance", "technology", "national_security"],
                tier="T2", source_kind="investigative_publisher",
                permitted_use="discovery_and_interpretation", corroboration_required=True,
                membership_content="exclude", extract_outbound_evidence_links=True,
                rate_limit={"requests_per_second": 0.2},
                feeds_topic="Investigative Documents & Public Records",
                feeds_key="rss_sources", enabled=True),
            src(id="unlimited_hangout_newsletter", name="Unlimited Hangout newsletter",
                publisher="Unlimited Hangout", homepage="https://newsletter.unlimitedhangout.com/",
                adapter="rss", endpoints=["https://newsletter.unlimitedhangout.com/rss/"],
                topics=["investigations"], tier="T2", source_kind="investigative_publisher",
                permitted_use="discovery_and_interpretation", corroboration_required=True,
                membership_content="exclude",
                feeds_topic="Investigative Documents & Public Records",
                feeds_key="rss_sources", enabled=True,
                notes="Validated public RSS on 2026-08-15. Membership content excluded."),
            src(id="unlimited_hangout_podcast_rssblue", name="Unlimited Hangout podcast (RSSBlue)",
                publisher="Unlimited Hangout", homepage="https://unlimitedhangout.com/",
                adapter="rss", endpoints=["https://feeds.rssblue.com/unlimited-hangout"],
                topics=["investigations"], tier="T2", source_kind="podcast",
                permitted_use="discovery_and_interpretation",
                disabled_reason="Endpoint returned HTTP 404 on 2026-08-15; do not pretend it is monitored"),
            src(id="corbett_report_site", name="The Corbett Report",
                publisher="The Corbett Report", homepage="https://corbettreport.com/",
                adapter="rss", endpoints=["https://corbettreport.com/feed/"],
                topics=["investigations", "media"], tier="T3",
                source_kind="analysis", permitted_use="discovery_only",
                corroboration_required=True, extract_outbound_evidence_links=True,
                feeds_topic="Investigative Documents & Public Records",
                feeds_key="rss_sources", enabled=True,
                notes="Official directory https://corbettreport.com/rssfeeds/. Main feed validated."),
            src(id="corbett_report_articles", name="Corbett Report articles",
                publisher="The Corbett Report", homepage="https://corbettreport.com/",
                adapter="rss", endpoints=["https://corbettreport.com/category/articles/feed/"],
                topics=["investigations"], tier="T3", source_kind="analysis",
                permitted_use="discovery_only",
                disabled_reason="Subset of main site feed; kept dark until yield is measured"),
            src(id="corbett_report_videos", name="Corbett Report videos",
                publisher="The Corbett Report", homepage="https://corbettreport.com/",
                adapter="rss", endpoints=["https://corbettreport.com/category/videos/feed/"],
                topics=["investigations"], tier="T3", source_kind="analysis",
                permitted_use="discovery_only",
                disabled_reason="Validated but held out of daily rotation to avoid duplicating the main feed"),
            src(id="corbett_report_interviews", name="Corbett Report interviews",
                publisher="The Corbett Report", homepage="https://corbettreport.com/",
                adapter="rss", endpoints=["https://corbettreport.com/category/interviews/feed/"],
                topics=["investigations"], tier="T3", source_kind="analysis",
                permitted_use="discovery_only",
                disabled_reason="Validated but held out of daily rotation to avoid duplicating the main feed"),
            src(id="corbett_report_podcast", name="Corbett Report podcast",
                publisher="The Corbett Report", homepage="https://corbettreport.com/",
                adapter="rss", endpoints=["https://www.corbettreport.com/feed/podcast/"],
                topics=["investigations"], tier="T3", source_kind="podcast",
                permitted_use="discovery_only",
                disabled_reason="Validated; enable on weekly rotation after yield measurement"),
            src(id="us_right_to_know", name="U.S. Right to Know",
                publisher="U.S. Right to Know", homepage="https://usrtk.org/",
                adapter="rss", endpoints=["https://usrtk.org/feed/"],
                topics=["investigations", "health", "foia"], tier="T2",
                source_kind="investigative_organization", permitted_use="documentary_lead",
                corroboration_required=True, extract_outbound_evidence_links=True,
                feeds_topic="Investigative Documents & Public Records",
                feeds_key="rss_sources", enabled=True,
                notes="Health claims require scientific/regulatory corroboration."),
            src(id="the_black_vault_documentarchive", name="The Black Vault document archive",
                publisher="The Black Vault", homepage="https://www.theblackvault.com/documentarchive/",
                adapter="rss", endpoints=["https://www.theblackvault.com/documentarchive/feed/"],
                topics=["foia", "declassified_documents"], tier="T1",
                source_kind="document_archive", permitted_use="documentary_lead",
                classify_attachments_independently=True, extract_document_metadata=True,
                extract_outbound_evidence_links=True,
                automatic_content_eligible=False, automatic_evidence_promotion=False,
                feeds_topic="Investigative Documents & Public Records",
                feeds_key="rss_sources", enabled=True,
                notes="Archive page is T1/T2; attached government records are classified independently."),
            src(id="the_black_vault_casefiles", name="The Black Vault casefiles",
                publisher="The Black Vault", homepage="https://www.theblackvault.com/",
                adapter="rss", endpoints=["https://www.theblackvault.com/casefiles/feed/"],
                topics=["foia"], tier="T2", source_kind="document_archive",
                permitted_use="documentary_lead", extract_outbound_evidence_links=True,
                feeds_topic="Investigative Documents & Public Records",
                feeds_key="rss_sources", enabled=True),
            src(id="national_security_archive", name="National Security Archive",
                publisher="George Washington University", homepage="https://nsarchive.gwu.edu/",
                adapter="site_change", endpoints=["https://nsarchive.gwu.edu/"],
                topics=["declassified_documents", "foreign_policy", "national_security"],
                regions=["global", "US"], tier="T1", source_kind="document_archive",
                permitted_use="documentary_lead", classify_attachments_independently=True,
                extract_document_metadata=True, corroboration_required=False,
                license_or_terms_url="https://nsarchive.gwu.edu/",
                rate_limit={"requests_per_second": 0.2},
                disabled_reason="No verified RSS; site_change adapter not in daily_run"),
            src(id="muckrock", name="MuckRock",
                publisher="MuckRock", homepage="https://www.muckrock.com/",
                adapter="foia_archive", endpoints=["https://www.muckrock.com/"],
                topics=["foia"], regions=["US"], tier="T2",
                source_kind="foia_platform", permitted_use="documentary_lead",
                license_or_terms_url="https://www.muckrock.com/terms/",
                disabled_reason="No verified public RSS; foia_archive adapter not in daily_run"),
            src(id="the_grayzone", name="The Grayzone",
                publisher="The Grayzone", homepage="https://thegrayzone.com/",
                adapter="rss", endpoints=["https://thegrayzone.com/feed/"],
                topics=["investigations", "geopolitics"], tier="T3",
                source_kind="commentary", permitted_use="discovery_only",
                corroboration_required=True, extract_outbound_evidence_links=True,
                feeds_topic="Investigative Documents & Public Records",
                feeds_key="rss_sources", enabled=True,
                notes="Discovery only until cited records and independent context are retrieved."),
            src(id="ddosecrets_catalog", name="Distributed Denial of Secrets",
                publisher="Distributed Denial of Secrets", homepage="https://ddosecrets.org/",
                adapter="site_change", endpoints=["https://ddosecrets.org/"],
                topics=["leaks", "public_interest_documents", "cybersecurity"],
                tier="T4", source_kind="restricted_archive_catalog",
                permitted_use="metadata_discovery_only", download_attachments=False,
                extract_personal_data=False, human_legal_security_review_required=True,
                corroboration_required=True, rate_limit={"requests_per_second": 0.1},
                license_or_terms_url="https://ddosecrets.org/",
                disabled_reason="Metadata-only catalog; requires legal/security approval before any collection"),
            src(id="ian_carroll_site", name="Ian Carroll",
                publisher="Ian Carroll", homepage="https://iancarroll.org/",
                adapter="site_change", endpoints=["https://iancarroll.org/"],
                topics=["commentary"], tier="T4", source_kind="commentary",
                permitted_use="discovery_only", collection_mode="discovery_only",
                license_or_terms_url="https://iancarroll.org/",
                disabled_reason="No verified RSS; site_change not in daily_run; never auto-promote claims"),
            src(id="ian_carroll_alias_candidate", name="Ian Carroll alias candidate",
                publisher="Ian Carroll", homepage="https://www.canceliancarroll.com/",
                adapter="site_change", endpoints=["https://www.canceliancarroll.com/"],
                topics=["commentary"], tier="T4", source_kind="commentary",
                permitted_use="discovery_only",
                license_or_terms_url="https://www.canceliancarroll.com/",
                disabled_reason="Candidate alias until HTTPS fetch, redirect target, and ownership pass validation"),
            src(id="david_icke_manual_watch", name="David Icke",
                publisher="David Icke", homepage="https://davidicke.com/",
                adapter="site_change", endpoints=["https://davidicke.com/"],
                topics=["alternative_commentary"], tier="T5", source_kind="commentary",
                permitted_use="quarantined_discovery", automatic_content_eligible=False,
                automatic_evidence_promotion=False, corroboration_required=True,
                collection_mode="manual_link_watch", rate_limit={"requests_per_second": 0.1},
                license_or_terms_url="https://davidicke.com/",
                disabled_reason="manual-monitor-only until explicit operator activation"),
        ],
        "Investigative journalism and document-discovery sources. T4/T5 cannot become content-eligible from discovery alone.",
    )

    dump(
        "social_watch.yaml",
        [
            src(id="x_whitney_webb", name="Whitney Webb on X",
                publisher="Whitney Webb", homepage="https://x.com/_whitneywebb",
                adapter="manual_link_watch", endpoints=["_whitneywebb"],
                topics=["investigations"], tier="T4", source_kind="social_profile",
                permitted_use="discovery_only", collection_mode="manual_link_watch",
                disabled_reason="No compliant free X API; identity watch only"),
            src(id="x_theblackvault", name="The Black Vault on X",
                publisher="The Black Vault", homepage="https://x.com/theblackvault",
                adapter="manual_link_watch", endpoints=["theblackvault"],
                topics=["foia"], tier="T4", source_kind="social_profile",
                permitted_use="discovery_only", collection_mode="manual_link_watch",
                disabled_reason="No compliant free X API; identity watch only"),
            src(id="x_thegrayzone", name="The Grayzone on X",
                publisher="The Grayzone", homepage="https://x.com/TheGrayzoneNews",
                adapter="manual_link_watch", endpoints=["TheGrayzoneNews"],
                topics=["investigations"], tier="T4", source_kind="social_profile",
                permitted_use="discovery_only", collection_mode="manual_link_watch",
                disabled_reason="No compliant free X API; identity watch only"),
            src(id="x_max_blumenthal", name="Max Blumenthal on X",
                publisher="Max Blumenthal", homepage="https://x.com/MaxBlumenthal",
                adapter="manual_link_watch", endpoints=["MaxBlumenthal"],
                topics=["investigations"], tier="T4", source_kind="social_profile",
                permitted_use="discovery_only", collection_mode="manual_link_watch",
                disabled_reason="No compliant free X API; identity watch only"),
            src(id="x_ian_carroll", name="Ian Carroll on X",
                publisher="Ian Carroll", homepage="https://x.com/IanCarrollShow",
                adapter="manual_link_watch", endpoints=["IanCarrollShow"],
                topics=["commentary"], tier="T4", source_kind="social_profile",
                permitted_use="discovery_only", collection_mode="manual_link_watch",
                disabled_reason="No compliant free X API; identity watch only"),
            src(id="x_david_icke", name="David Icke on X",
                publisher="David Icke", homepage="https://x.com/davidicke",
                adapter="manual_link_watch", endpoints=["davidicke"],
                topics=["alternative_commentary"], tier="T5", source_kind="social_profile",
                permitted_use="quarantined_discovery", collection_mode="manual_link_watch",
                automatic_content_eligible=False, automatic_evidence_promotion=False,
                disabled_reason="T5 quarantine; identity watch only"),
            src(id="twitch_ian_carroll", name="Ian Carroll on Twitch",
                publisher="Ian Carroll", homepage="https://www.twitch.tv/canceliancarroll",
                adapter="twitch", endpoints=["canceliancarroll"],
                topics=["commentary"], tier="T4", source_kind="livestream",
                permitted_use="discovery_only", collection_mode="manual_link_watch",
                disabled_reason="No free reliable Twitch collection in GitHub Actions"),
            *[
                src(id=sid, name=name, publisher=name, homepage=f"https://x.com/{handle}",
                    adapter="manual_link_watch", endpoints=[handle],
                    topics=["ai"] if "ai" in sid or handle in {"Sauain","_kaitoai","Marktechpost","levelsio","SwiftOnSecurity"} else ["crypto"],
                    tier="T4", source_kind="social_profile", permitted_use="discovery_only",
                    collection_mode="manual_link_watch",
                    disabled_reason="Existing feeds.yaml X identities; no automated collection")
                for sid, name, handle in [
                    ("x_sauain", "Sauain", "Sauain"),
                    ("x_levelsio", "levelsio", "levelsio"),
                    ("x_swiftonsecurity", "SwiftOnSecurity", "SwiftOnSecurity"),
                    ("x_kaitoai", "Kaito AI", "_kaitoai"),
                    ("x_marktechpost", "Marktechpost", "Marktechpost"),
                    ("x_a16zcrypto", "a16z crypto", "a16zcrypto"),
                    ("x_paradigm", "Paradigm", "paradigm"),
                    ("x_multicoin", "Multicoin Capital", "multicoincap"),
                    ("x_cointelegraph", "Cointelegraph", "cointelegraph"),
                    ("x_coinlaunchspace", "CoinLaunchSpace", "CoinLaunchSpace"),
                    ("x_timbeiko", "Tim Beiko", "TimBeiko"),
                ]
            ],
        ],
        "Social/livestream identities. Recorded for watch metadata; not collected by Actions.",
    )

    dump(
        "ai_experts.yaml",
        [
            src(id="simon_willison", name="Simon Willison", publisher="Simon Willison",
                homepage="https://simonwillison.net/", adapter="rss",
                endpoints=["https://simonwillison.net/atom/everything/"],
                topics=["ai", "ai_agents"], tier="T2", source_kind="expert_interpretation",
                permitted_use="discovery_and_interpretation",
                disabled_reason="Wave C expert feed; enable after quota/yield review"),
            src(id="chip_huyen", name="Chip Huyen", publisher="Chip Huyen",
                homepage="https://huyenchip.com/", adapter="site_change",
                endpoints=["https://huyenchip.com/blog/"],
                topics=["ai"], tier="T2", source_kind="expert_interpretation",
                permitted_use="discovery_and_interpretation",
                license_or_terms_url="https://huyenchip.com/",
                disabled_reason="No verified RSS in this rollout"),
            src(id="import_ai", name="Import AI / Jack Clark", publisher="Jack Clark",
                homepage="https://importai.substack.com/", adapter="rss",
                endpoints=["https://importai.substack.com/feed"],
                topics=["ai"], tier="T2", source_kind="expert_interpretation",
                permitted_use="discovery_and_interpretation",
                disabled_reason="Wave C expert feed; enable after quota/yield review"),
        ],
        "T2 expert interpretation. Follow links to code/papers before treating as evidence.",
    )


if __name__ == "__main__":
    main()
